"""Make intra_id for BannedUser no longer unique

Revision ID: 236a9b044dfb
Revises: 52905ae9ebee
Create Date: 2019-09-04 19:21:16.467688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236a9b044dfb'
down_revision = '52905ae9ebee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_banned_user_intra_id', table_name='banned_user')
    op.create_index(op.f('ix_banned_user_intra_id'), 'banned_user', ['intra_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banned_user_intra_id'), table_name='banned_user')
    op.create_index('ix_banned_user_intra_id', 'banned_user', ['intra_id'], unique=1)
    # ### end Alembic commands ###
