"""Add visible field to retain deleted records

Revision ID: 52905ae9ebee
Revises: a65cab2e21ae
Create Date: 2019-09-04 19:03:32.465416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52905ae9ebee'
down_revision = 'a65cab2e21ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_user', sa.Column('visible', sa.Boolean(), nullable=True))
    op.add_column('staff_member', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_member', 'visible')
    op.drop_column('banned_user', 'visible')
    # ### end Alembic commands ###
