"""banned users table

Revision ID: 7ba249970f5a
Revises: 
Create Date: 2019-08-21 19:29:19.499395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba249970f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banned_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intra_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banned_user_first_name'), 'banned_user', ['first_name'], unique=False)
    op.create_index(op.f('ix_banned_user_intra_id'), 'banned_user', ['intra_id'], unique=True)
    op.create_index(op.f('ix_banned_user_last_name'), 'banned_user', ['last_name'], unique=False)
    op.create_index(op.f('ix_banned_user_timestamp'), 'banned_user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banned_user_timestamp'), table_name='banned_user')
    op.drop_index(op.f('ix_banned_user_last_name'), table_name='banned_user')
    op.drop_index(op.f('ix_banned_user_intra_id'), table_name='banned_user')
    op.drop_index(op.f('ix_banned_user_first_name'), table_name='banned_user')
    op.drop_table('banned_user')
    # ### end Alembic commands ###
