"""Add StaffMember model

Revision ID: a65cab2e21ae
Revises: e7f0b30ef8e8
Create Date: 2019-09-02 00:16:40.227208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65cab2e21ae'
down_revision = 'e7f0b30ef8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('slack', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_member_email'), 'staff_member', ['email'], unique=False)
    op.create_index(op.f('ix_staff_member_first_name'), 'staff_member', ['first_name'], unique=False)
    op.create_index(op.f('ix_staff_member_last_name'), 'staff_member', ['last_name'], unique=False)
    op.create_index(op.f('ix_staff_member_phone'), 'staff_member', ['phone'], unique=False)
    op.create_index(op.f('ix_staff_member_role'), 'staff_member', ['role'], unique=False)
    op.create_index(op.f('ix_staff_member_slack'), 'staff_member', ['slack'], unique=False)
    op.create_index(op.f('ix_staff_member_timestamp'), 'staff_member', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_member_timestamp'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_slack'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_role'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_phone'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_last_name'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_first_name'), table_name='staff_member')
    op.drop_index(op.f('ix_staff_member_email'), table_name='staff_member')
    op.drop_table('staff_member')
    # ### end Alembic commands ###
